version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      react-router:
        patterns:
          - "@react-router/dev"
          - "@react-router/fs-routes"
          - "@react-router/node"
          - "@react-router/serve"
          - "react-router"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
