packages:
  - "apps/*"
  - "config/*"
  - "packages/*"

# Don't install packages that are less than 1 day old
# This reduces the risk of installing compromised packages.
# In most cases, malicious releases are discovered and removed from the registry
# within an hour.
# see: https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - "@types/react"
  - "@types/react-dom"
  - "react"
  - "react-dom"
  - "typescript"

catalog:
  "@phosphor-icons/react": "2.1.10"
  "@react-router/dev": "7.9.3"
  "@react-router/fs-routes": "7.9.3"
  "@react-router/node": "7.9.3"
  "@react-router/serve": "7.9.3"
  "@types/react-dom": "18.3.7"
  "@types/react": "18.3.25"
  "react-dom": "18.3.1"
  "react-router": "7.9.3"
  "react": "18.3.1"
  "tailwindcss": "4.1.14"
  "typescript": "5.9.3"
  "vite": "7.1.9"
