packages:
  - "apps/*"
  - "config/*"
  - "packages/*"

# Don't install packages that are less than 6h old
# This reduces the risk of installing compromised packages.
# In most cases, malicious releases are discovered and removed from the registry
# within an hour.
# see: https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 360

minimumReleaseAgeExclude:
  - "@ngrok/remark-mdx-github-alerts"
  - "@ngrok/remark-mdx-no-paragraph-wrap"
  - "@types/react"
  - "@types/react-dom"
  - "react"
  - "react-dom"
  - "typescript"

catalog:
  "@phosphor-icons/react": "2.1.10"
  "happy-dom": "20.6.3"
  "tailwindcss": "4.2.0"
  "typescript": "5.9.3"
  "vite": "7.3.1"
