/** @type {import('tailwindcss').Config} */
module.exports = {
	important: "#ngrok",
	content: [
		"./pages/**/*.{ts,tsx}",
		"./components/**/*.{ts,tsx}",
		"./app/**/*.{ts,tsx}",
		"./src/**/*.{ts,tsx}",
	],
	theme: {
		container: {
			center: true,
			padding: "2rem",
			screens: {
				"2xl": "1400px",
			},
		},
		extend: {
			colors: {
				white: "hsl(var(--white) / <alpha-value>)",
				neutral: {
					50: "hsl(var(--neutral-050) / <alpha-value>)",
					100: "hsl(var(--neutral-100) / <alpha-value>)",
					200: "hsl(var(--neutral-200) / <alpha-value>)",
					300: "hsl(var(--neutral-300) / <alpha-value>)",
					400: "hsl(var(--neutral-400) / <alpha-value>)",
					500: "hsl(var(--neutral-500) / <alpha-value>)",
					600: "hsl(var(--neutral-600) / <alpha-value>)",
					700: "hsl(var(--neutral-700) / <alpha-value>)",
					800: "hsl(var(--neutral-800) / <alpha-value>)",
					900: "hsl(var(--neutral-900) / <alpha-value>)",
				},
				danger: {
					50: "hsl(var(--danger-050) / <alpha-value>)",
					100: "hsl(var(--danger-100) / <alpha-value>)",
					200: "hsl(var(--danger-200) / <alpha-value>)",
					300: "hsl(var(--danger-300) / <alpha-value>)",
					400: "hsl(var(--danger-400) / <alpha-value>)",
					500: "hsl(var(--danger-500) / <alpha-value>)",
					600: "hsl(var(--danger-600) / <alpha-value>)",
					700: "hsl(var(--danger-700) / <alpha-value>)",
					800: "hsl(var(--danger-800) / <alpha-value>)",
					900: "hsl(var(--danger-900) / <alpha-value>)",
				},
				warning: {
					50: "hsl(var(--warning-050) / <alpha-value>)",
					100: "hsl(var(--warning-100) / <alpha-value>)",
					200: "hsl(var(--warning-200) / <alpha-value>)",
					300: "hsl(var(--warning-300) / <alpha-value>)",
					400: "hsl(var(--warning-400) / <alpha-value>)",
					500: "hsl(var(--warning-500) / <alpha-value>)",
					600: "hsl(var(--warning-600) / <alpha-value>)",
					700: "hsl(var(--warning-700) / <alpha-value>)",
					800: "hsl(var(--warning-800) / <alpha-value>)",
					900: "hsl(var(--warning-900) / <alpha-value>)",
				},
				success: {
					50: "hsl(var(--success-050) / <alpha-value>)",
					100: "hsl(var(--success-100) / <alpha-value>)",
					200: "hsl(var(--success-200) / <alpha-value>)",
					300: "hsl(var(--success-300) / <alpha-value>)",
					400: "hsl(var(--success-400) / <alpha-value>)",
					500: "hsl(var(--success-500) / <alpha-value>)",
					600: "hsl(var(--success-600) / <alpha-value>)",
					700: "hsl(var(--success-700) / <alpha-value>)",
					800: "hsl(var(--success-800) / <alpha-value>)",
					900: "hsl(var(--success-900) / <alpha-value>)",
				},
				"brand-primary": {
					50: "hsl(var(--brand-primary-050) / <alpha-value>)",
					100: "hsl(var(--brand-primary-100) / <alpha-value>)",
					200: "hsl(var(--brand-primary-200) / <alpha-value>)",
					300: "hsl(var(--brand-primary-300) / <alpha-value>)",
					400: "hsl(var(--brand-primary-400) / <alpha-value>)",
					500: "hsl(var(--brand-primary-500) / <alpha-value>)",
					600: "hsl(var(--brand-primary-600) / <alpha-value>)",
					700: "hsl(var(--brand-primary-700) / <alpha-value>)",
					800: "hsl(var(--brand-primary-800) / <alpha-value>)",
					900: "hsl(var(--brand-primary-900) / <alpha-value>)",
				},
				"brand-secondary": {
					50: "hsl(var(--brand-secondary-050) / <alpha-value>)",
					100: "hsl(var(--brand-secondary-100) / <alpha-value>)",
					200: "hsl(var(--brand-secondary-200) / <alpha-value>)",
					300: "hsl(var(--brand-secondary-300) / <alpha-value>)",
					400: "hsl(var(--brand-secondary-400) / <alpha-value>)",
					500: "hsl(var(--brand-secondary-500) / <alpha-value>)",
					600: "hsl(var(--brand-secondary-600) / <alpha-value>)",
					700: "hsl(var(--brand-secondary-700) / <alpha-value>)",
					800: "hsl(var(--brand-secondary-800) / <alpha-value>)",
					900: "hsl(var(--brand-secondary-900) / <alpha-value>)",
				},
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			keyframes: {
				"accordion-down": {
					from: { height: 0 },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: 0 },
				},
			},
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
};
