import type { Config } from "tailwindcss";
import tailwindCssAnimatePlugin from "tailwindcss-animate";
import defaultTheme from "tailwindcss/defaultTheme";
import plugin from "tailwindcss/plugin";
import { firefoxVariantPlugin } from "./tailwind-plugin-firefox-variant.js";

const mantlePreset = {
	content: [],
	darkMode: "class",
	theme: {
		colors: {
			inherit: "inherit",
			current: "currentColor",
			transparent: "transparent",
			white: "hsl(var(--white) / <alpha-value>)",
			black: "hsl(var(--black) / <alpha-value>)",
			gray: {
				50: "hsl(var(--gray-50) / <alpha-value>)",
				100: "hsl(var(--gray-100) / <alpha-value>)",
				200: "hsl(var(--gray-200) / <alpha-value>)",
				300: "hsl(var(--gray-300) / <alpha-value>)",
				400: "hsl(var(--gray-400) / <alpha-value>)",
				500: "hsl(var(--gray-500) / <alpha-value>)",
				600: "hsl(var(--gray-600) / <alpha-value>)",
				700: "hsl(var(--gray-700) / <alpha-value>)",
				800: "hsl(var(--gray-800) / <alpha-value>)",
				900: "hsl(var(--gray-900) / <alpha-value>)",
				950: "hsl(var(--gray-950) / <alpha-value>)",
				"a50": "hsl(var(--gray-a50))",
				"a100": "hsl(var(--gray-a100))",
				"a200": "hsl(var(--gray-a200))",
				"a300": "hsl(var(--gray-a300))",
				"a400": "hsl(var(--gray-a400))",
			},
			red: {
				50: "hsl(var(--red-50) / <alpha-value>)",
				100: "hsl(var(--red-100) / <alpha-value>)",
				200: "hsl(var(--red-200) / <alpha-value>)",
				300: "hsl(var(--red-300) / <alpha-value>)",
				400: "hsl(var(--red-400) / <alpha-value>)",
				500: "hsl(var(--red-500) / <alpha-value>)",
				600: "hsl(var(--red-600) / <alpha-value>)",
				700: "hsl(var(--red-700) / <alpha-value>)",
				800: "hsl(var(--red-800) / <alpha-value>)",
				900: "hsl(var(--red-900) / <alpha-value>)",
				950: "hsl(var(--red-950) / <alpha-value>)",
				"a50": "hsl(var(--red-a50))",
				"a100": "hsl(var(--red-a100))",
				"a200": "hsl(var(--red-a200))",
				"a300": "hsl(var(--red-a300))",
				"a400": "hsl(var(--red-a400))",
			},
			orange: {
				50: "hsl(var(--orange-50) / <alpha-value>)",
				100: "hsl(var(--orange-100) / <alpha-value>)",
				200: "hsl(var(--orange-200) / <alpha-value>)",
				300: "hsl(var(--orange-300) / <alpha-value>)",
				400: "hsl(var(--orange-400) / <alpha-value>)",
				500: "hsl(var(--orange-500) / <alpha-value>)",
				600: "hsl(var(--orange-600) / <alpha-value>)",
				700: "hsl(var(--orange-700) / <alpha-value>)",
				800: "hsl(var(--orange-800) / <alpha-value>)",
				900: "hsl(var(--orange-900) / <alpha-value>)",
				950: "hsl(var(--orange-950) / <alpha-value>)",
				"a50": "hsl(var(--orange-a50))",
				"a100": "hsl(var(--orange-a100))",
				"a200": "hsl(var(--orange-a200))",
				"a300": "hsl(var(--orange-a300))",
				"a400": "hsl(var(--orange-a400))",
			},
			amber: {
				50: "hsl(var(--amber-50) / <alpha-value>)",
				100: "hsl(var(--amber-100) / <alpha-value>)",
				200: "hsl(var(--amber-200) / <alpha-value>)",
				300: "hsl(var(--amber-300) / <alpha-value>)",
				400: "hsl(var(--amber-400) / <alpha-value>)",
				500: "hsl(var(--amber-500) / <alpha-value>)",
				600: "hsl(var(--amber-600) / <alpha-value>)",
				700: "hsl(var(--amber-700) / <alpha-value>)",
				800: "hsl(var(--amber-800) / <alpha-value>)",
				900: "hsl(var(--amber-900) / <alpha-value>)",
				950: "hsl(var(--amber-950) / <alpha-value>)",
				"a50": "hsl(var(--amber-a50))",
				"a100": "hsl(var(--amber-a100))",
				"a200": "hsl(var(--amber-a200))",
				"a300": "hsl(var(--amber-a300))",
				"a400": "hsl(var(--amber-a400))",
			},
			yellow: {
				50: "hsl(var(--yellow-50) / <alpha-value>)",
				100: "hsl(var(--yellow-100) / <alpha-value>)",
				200: "hsl(var(--yellow-200) / <alpha-value>)",
				300: "hsl(var(--yellow-300) / <alpha-value>)",
				400: "hsl(var(--yellow-400) / <alpha-value>)",
				500: "hsl(var(--yellow-500) / <alpha-value>)",
				600: "hsl(var(--yellow-600) / <alpha-value>)",
				700: "hsl(var(--yellow-700) / <alpha-value>)",
				800: "hsl(var(--yellow-800) / <alpha-value>)",
				900: "hsl(var(--yellow-900) / <alpha-value>)",
				950: "hsl(var(--yellow-950) / <alpha-value>)",
				"a50": "hsl(var(--yellow-a50))",
				"a100": "hsl(var(--yellow-a100))",
				"a200": "hsl(var(--yellow-a200))",
				"a300": "hsl(var(--yellow-a300))",
				"a400": "hsl(var(--yellow-a400))",
			},
			lime: {
				50: "hsl(var(--lime-50) / <alpha-value>)",
				100: "hsl(var(--lime-100) / <alpha-value>)",
				200: "hsl(var(--lime-200) / <alpha-value>)",
				300: "hsl(var(--lime-300) / <alpha-value>)",
				400: "hsl(var(--lime-400) / <alpha-value>)",
				500: "hsl(var(--lime-500) / <alpha-value>)",
				600: "hsl(var(--lime-600) / <alpha-value>)",
				700: "hsl(var(--lime-700) / <alpha-value>)",
				800: "hsl(var(--lime-800) / <alpha-value>)",
				900: "hsl(var(--lime-900) / <alpha-value>)",
				950: "hsl(var(--lime-950) / <alpha-value>)",
				"a50": "hsl(var(--lime-a50))",
				"a100": "hsl(var(--lime-a100))",
				"a200": "hsl(var(--lime-a200))",
				"a300": "hsl(var(--lime-a300))",
				"a400": "hsl(var(--lime-a400))",
			},
			green: {
				50: "hsl(var(--green-50) / <alpha-value>)",
				100: "hsl(var(--green-100) / <alpha-value>)",
				200: "hsl(var(--green-200) / <alpha-value>)",
				300: "hsl(var(--green-300) / <alpha-value>)",
				400: "hsl(var(--green-400) / <alpha-value>)",
				500: "hsl(var(--green-500) / <alpha-value>)",
				600: "hsl(var(--green-600) / <alpha-value>)",
				700: "hsl(var(--green-700) / <alpha-value>)",
				800: "hsl(var(--green-800) / <alpha-value>)",
				900: "hsl(var(--green-900) / <alpha-value>)",
				950: "hsl(var(--green-950) / <alpha-value>)",
				"a50": "hsl(var(--green-a50))",
				"a100": "hsl(var(--green-a100))",
				"a200": "hsl(var(--green-a200))",
				"a300": "hsl(var(--green-a300))",
				"a400": "hsl(var(--green-a400))",
			},
			emerald: {
				50: "hsl(var(--emerald-50) / <alpha-value>)",
				100: "hsl(var(--emerald-100) / <alpha-value>)",
				200: "hsl(var(--emerald-200) / <alpha-value>)",
				300: "hsl(var(--emerald-300) / <alpha-value>)",
				400: "hsl(var(--emerald-400) / <alpha-value>)",
				500: "hsl(var(--emerald-500) / <alpha-value>)",
				600: "hsl(var(--emerald-600) / <alpha-value>)",
				700: "hsl(var(--emerald-700) / <alpha-value>)",
				800: "hsl(var(--emerald-800) / <alpha-value>)",
				900: "hsl(var(--emerald-900) / <alpha-value>)",
				950: "hsl(var(--emerald-950) / <alpha-value>)",
				"a50": "hsl(var(--emerald-a50))",
				"a100": "hsl(var(--emerald-a100))",
				"a200": "hsl(var(--emerald-a200))",
				"a300": "hsl(var(--emerald-a300))",
				"a400": "hsl(var(--emerald-a400))",
			},
			teal: {
				50: "hsl(var(--teal-50) / <alpha-value>)",
				100: "hsl(var(--teal-100) / <alpha-value>)",
				200: "hsl(var(--teal-200) / <alpha-value>)",
				300: "hsl(var(--teal-300) / <alpha-value>)",
				400: "hsl(var(--teal-400) / <alpha-value>)",
				500: "hsl(var(--teal-500) / <alpha-value>)",
				600: "hsl(var(--teal-600) / <alpha-value>)",
				700: "hsl(var(--teal-700) / <alpha-value>)",
				800: "hsl(var(--teal-800) / <alpha-value>)",
				900: "hsl(var(--teal-900) / <alpha-value>)",
				950: "hsl(var(--teal-950) / <alpha-value>)",
				"a50": "hsl(var(--teal-a50))",
				"a100": "hsl(var(--teal-a100))",
				"a200": "hsl(var(--teal-a200))",
				"a300": "hsl(var(--teal-a300))",
				"a400": "hsl(var(--teal-a400))",
			},
			cyan: {
				50: "hsl(var(--cyan-50) / <alpha-value>)",
				100: "hsl(var(--cyan-100) / <alpha-value>)",
				200: "hsl(var(--cyan-200) / <alpha-value>)",
				300: "hsl(var(--cyan-300) / <alpha-value>)",
				400: "hsl(var(--cyan-400) / <alpha-value>)",
				500: "hsl(var(--cyan-500) / <alpha-value>)",
				600: "hsl(var(--cyan-600) / <alpha-value>)",
				700: "hsl(var(--cyan-700) / <alpha-value>)",
				800: "hsl(var(--cyan-800) / <alpha-value>)",
				900: "hsl(var(--cyan-900) / <alpha-value>)",
				950: "hsl(var(--cyan-950) / <alpha-value>)",
				"a50": "hsl(var(--cyan-a50))",
				"a100": "hsl(var(--cyan-a100))",
				"a200": "hsl(var(--cyan-a200))",
				"a300": "hsl(var(--cyan-a300))",
				"a400": "hsl(var(--cyan-a400))",
			},
			sky: {
				50: "hsl(var(--sky-50) / <alpha-value>)",
				100: "hsl(var(--sky-100) / <alpha-value>)",
				200: "hsl(var(--sky-200) / <alpha-value>)",
				300: "hsl(var(--sky-300) / <alpha-value>)",
				400: "hsl(var(--sky-400) / <alpha-value>)",
				500: "hsl(var(--sky-500) / <alpha-value>)",
				600: "hsl(var(--sky-600) / <alpha-value>)",
				700: "hsl(var(--sky-700) / <alpha-value>)",
				800: "hsl(var(--sky-800) / <alpha-value>)",
				900: "hsl(var(--sky-900) / <alpha-value>)",
				950: "hsl(var(--sky-950) / <alpha-value>)",
				"a50": "hsl(var(--sky-a50))",
				"a100": "hsl(var(--sky-a100))",
				"a200": "hsl(var(--sky-a200))",
				"a300": "hsl(var(--sky-a300))",
				"a400": "hsl(var(--sky-a400))",
			},
			blue: {
				50: "hsl(var(--blue-50) / <alpha-value>)",
				100: "hsl(var(--blue-100) / <alpha-value>)",
				200: "hsl(var(--blue-200) / <alpha-value>)",
				300: "hsl(var(--blue-300) / <alpha-value>)",
				400: "hsl(var(--blue-400) / <alpha-value>)",
				500: "hsl(var(--blue-500) / <alpha-value>)",
				600: "hsl(var(--blue-600) / <alpha-value>)",
				700: "hsl(var(--blue-700) / <alpha-value>)",
				800: "hsl(var(--blue-800) / <alpha-value>)",
				900: "hsl(var(--blue-900) / <alpha-value>)",
				950: "hsl(var(--blue-950) / <alpha-value>)",
				"a50": "hsl(var(--blue-a50))",
				"a100": "hsl(var(--blue-a100))",
				"a200": "hsl(var(--blue-a200))",
				"a300": "hsl(var(--blue-a300))",
				"a400": "hsl(var(--blue-a400))",
			},
			indigo: {
				50: "hsl(var(--indigo-50) / <alpha-value>)",
				100: "hsl(var(--indigo-100) / <alpha-value>)",
				200: "hsl(var(--indigo-200) / <alpha-value>)",
				300: "hsl(var(--indigo-300) / <alpha-value>)",
				400: "hsl(var(--indigo-400) / <alpha-value>)",
				500: "hsl(var(--indigo-500) / <alpha-value>)",
				600: "hsl(var(--indigo-600) / <alpha-value>)",
				700: "hsl(var(--indigo-700) / <alpha-value>)",
				800: "hsl(var(--indigo-800) / <alpha-value>)",
				900: "hsl(var(--indigo-900) / <alpha-value>)",
				950: "hsl(var(--indigo-950) / <alpha-value>)",
				"a50": "hsl(var(--indigo-a50))",
				"a100": "hsl(var(--indigo-a100))",
				"a200": "hsl(var(--indigo-a200))",
				"a300": "hsl(var(--indigo-a300))",
				"a400": "hsl(var(--indigo-a400))",
			},
			violet: {
				50: "hsl(var(--violet-50) / <alpha-value>)",
				100: "hsl(var(--violet-100) / <alpha-value>)",
				200: "hsl(var(--violet-200) / <alpha-value>)",
				300: "hsl(var(--violet-300) / <alpha-value>)",
				400: "hsl(var(--violet-400) / <alpha-value>)",
				500: "hsl(var(--violet-500) / <alpha-value>)",
				600: "hsl(var(--violet-600) / <alpha-value>)",
				700: "hsl(var(--violet-700) / <alpha-value>)",
				800: "hsl(var(--violet-800) / <alpha-value>)",
				900: "hsl(var(--violet-900) / <alpha-value>)",
				950: "hsl(var(--violet-950) / <alpha-value>)",
				"a50": "hsl(var(--violet-a50))",
				"a100": "hsl(var(--violet-a100))",
				"a200": "hsl(var(--violet-a200))",
				"a300": "hsl(var(--violet-a300))",
				"a400": "hsl(var(--violet-a400))",
			},
			purple: {
				50: "hsl(var(--purple-50) / <alpha-value>)",
				100: "hsl(var(--purple-100) / <alpha-value>)",
				200: "hsl(var(--purple-200) / <alpha-value>)",
				300: "hsl(var(--purple-300) / <alpha-value>)",
				400: "hsl(var(--purple-400) / <alpha-value>)",
				500: "hsl(var(--purple-500) / <alpha-value>)",
				600: "hsl(var(--purple-600) / <alpha-value>)",
				700: "hsl(var(--purple-700) / <alpha-value>)",
				800: "hsl(var(--purple-800) / <alpha-value>)",
				900: "hsl(var(--purple-900) / <alpha-value>)",
				950: "hsl(var(--purple-950) / <alpha-value>)",
				"a50": "hsl(var(--purple-a50))",
				"a100": "hsl(var(--purple-a100))",
				"a200": "hsl(var(--purple-a200))",
				"a300": "hsl(var(--purple-a300))",
				"a400": "hsl(var(--purple-a400))",
			},
			fuchsia: {
				50: "hsl(var(--fuchsia-50) / <alpha-value>)",
				100: "hsl(var(--fuchsia-100) / <alpha-value>)",
				200: "hsl(var(--fuchsia-200) / <alpha-value>)",
				300: "hsl(var(--fuchsia-300) / <alpha-value>)",
				400: "hsl(var(--fuchsia-400) / <alpha-value>)",
				500: "hsl(var(--fuchsia-500) / <alpha-value>)",
				600: "hsl(var(--fuchsia-600) / <alpha-value>)",
				700: "hsl(var(--fuchsia-700) / <alpha-value>)",
				800: "hsl(var(--fuchsia-800) / <alpha-value>)",
				900: "hsl(var(--fuchsia-900) / <alpha-value>)",
				950: "hsl(var(--fuchsia-950) / <alpha-value>)",
				"a50": "hsl(var(--fuchsia-a50))",
				"a100": "hsl(var(--fuchsia-a100))",
				"a200": "hsl(var(--fuchsia-a200))",
				"a300": "hsl(var(--fuchsia-a300))",
				"a400": "hsl(var(--fuchsia-a400))",
			},
			pink: {
				50: "hsl(var(--pink-50) / <alpha-value>)",
				100: "hsl(var(--pink-100) / <alpha-value>)",
				200: "hsl(var(--pink-200) / <alpha-value>)",
				300: "hsl(var(--pink-300) / <alpha-value>)",
				400: "hsl(var(--pink-400) / <alpha-value>)",
				500: "hsl(var(--pink-500) / <alpha-value>)",
				600: "hsl(var(--pink-600) / <alpha-value>)",
				700: "hsl(var(--pink-700) / <alpha-value>)",
				800: "hsl(var(--pink-800) / <alpha-value>)",
				900: "hsl(var(--pink-900) / <alpha-value>)",
				950: "hsl(var(--pink-950) / <alpha-value>)",
				"a50": "hsl(var(--pink-a50))",
				"a100": "hsl(var(--pink-a100))",
				"a200": "hsl(var(--pink-a200))",
				"a300": "hsl(var(--pink-a300))",
				"a400": "hsl(var(--pink-a400))",
			},
			rose: {
				50: "hsl(var(--rose-50) / <alpha-value>)",
				100: "hsl(var(--rose-100) / <alpha-value>)",
				200: "hsl(var(--rose-200) / <alpha-value>)",
				300: "hsl(var(--rose-300) / <alpha-value>)",
				400: "hsl(var(--rose-400) / <alpha-value>)",
				500: "hsl(var(--rose-500) / <alpha-value>)",
				600: "hsl(var(--rose-600) / <alpha-value>)",
				700: "hsl(var(--rose-700) / <alpha-value>)",
				800: "hsl(var(--rose-800) / <alpha-value>)",
				900: "hsl(var(--rose-900) / <alpha-value>)",
				950: "hsl(var(--rose-950) / <alpha-value>)",
				"a50": "hsl(var(--rose-a50))",
				"a100": "hsl(var(--rose-a100))",
				"a200": "hsl(var(--rose-a200))",
				"a300": "hsl(var(--rose-a300))",
				"a400": "hsl(var(--rose-a400))",
			},
			neutral: {
				DEFAULT: "hsl(var(--neutral-500) / <alpha-value>)",
				50: "hsl(var(--neutral-50) / <alpha-value>)",
				100: "hsl(var(--neutral-100) / <alpha-value>)",
				200: "hsl(var(--neutral-200) / <alpha-value>)",
				300: "hsl(var(--neutral-300) / <alpha-value>)",
				400: "hsl(var(--neutral-400) / <alpha-value>)",
				500: "hsl(var(--neutral-500) / <alpha-value>)",
				600: "hsl(var(--neutral-600) / <alpha-value>)",
				700: "hsl(var(--neutral-700) / <alpha-value>)",
				800: "hsl(var(--neutral-800) / <alpha-value>)",
				900: "hsl(var(--neutral-900) / <alpha-value>)",
				950: "hsl(var(--neutral-950) / <alpha-value>)",
				"a50": "hsl(var(--neutral-a50))",
				"a100": "hsl(var(--neutral-a100))",
				"a200": "hsl(var(--neutral-a200))",
				"a300": "hsl(var(--neutral-a300))",
				"a400": "hsl(var(--neutral-a400))",
			},
			accent: {
				DEFAULT: "hsl(var(--accent-500) / <alpha-value>)",
				50: "hsl(var(--accent-50) / <alpha-value>)",
				100: "hsl(var(--accent-100) / <alpha-value>)",
				200: "hsl(var(--accent-200) / <alpha-value>)",
				300: "hsl(var(--accent-300) / <alpha-value>)",
				400: "hsl(var(--accent-400) / <alpha-value>)",
				500: "hsl(var(--accent-500) / <alpha-value>)",
				600: "hsl(var(--accent-600) / <alpha-value>)",
				700: "hsl(var(--accent-700) / <alpha-value>)",
				800: "hsl(var(--accent-800) / <alpha-value>)",
				900: "hsl(var(--accent-900) / <alpha-value>)",
				950: "hsl(var(--accent-950) / <alpha-value>)",
				"a50": "hsl(var(--accent-a50))",
				"a100": "hsl(var(--accent-a100))",
				"a200": "hsl(var(--accent-a200))",
				"a300": "hsl(var(--accent-a300))",
				"a400": "hsl(var(--accent-a400))",
			},
			danger: {
				DEFAULT: "hsl(var(--danger-500) / <alpha-value>)",
				50: "hsl(var(--danger-50) / <alpha-value>)",
				100: "hsl(var(--danger-100) / <alpha-value>)",
				200: "hsl(var(--danger-200) / <alpha-value>)",
				300: "hsl(var(--danger-300) / <alpha-value>)",
				400: "hsl(var(--danger-400) / <alpha-value>)",
				500: "hsl(var(--danger-500) / <alpha-value>)",
				600: "hsl(var(--danger-600) / <alpha-value>)",
				700: "hsl(var(--danger-700) / <alpha-value>)",
				800: "hsl(var(--danger-800) / <alpha-value>)",
				900: "hsl(var(--danger-900) / <alpha-value>)",
				950: "hsl(var(--danger-950) / <alpha-value>)",
				"a50": "hsl(var(--danger-a50))",
				"a100": "hsl(var(--danger-a100))",
				"a200": "hsl(var(--danger-a200))",
				"a300": "hsl(var(--danger-a300))",
				"a400": "hsl(var(--danger-a400))",
			},
			warning: {
				DEFAULT: "hsl(var(--warning-500) / <alpha-value>)",
				50: "hsl(var(--warning-50) / <alpha-value>)",
				100: "hsl(var(--warning-100) / <alpha-value>)",
				200: "hsl(var(--warning-200) / <alpha-value>)",
				300: "hsl(var(--warning-300) / <alpha-value>)",
				400: "hsl(var(--warning-400) / <alpha-value>)",
				500: "hsl(var(--warning-500) / <alpha-value>)",
				600: "hsl(var(--warning-600) / <alpha-value>)",
				700: "hsl(var(--warning-700) / <alpha-value>)",
				800: "hsl(var(--warning-800) / <alpha-value>)",
				900: "hsl(var(--warning-900) / <alpha-value>)",
				950: "hsl(var(--warning-950) / <alpha-value>)",
				"a50": "hsl(var(--warning-a50))",
				"a100": "hsl(var(--warning-a100))",
				"a200": "hsl(var(--warning-a200))",
				"a300": "hsl(var(--warning-a300))",
				"a400": "hsl(var(--warning-a400))",
			},
			success: {
				DEFAULT: "hsl(var(--success-500) / <alpha-value>)",
				50: "hsl(var(--success-50) / <alpha-value>)",
				100: "hsl(var(--success-100) / <alpha-value>)",
				200: "hsl(var(--success-200) / <alpha-value>)",
				300: "hsl(var(--success-300) / <alpha-value>)",
				400: "hsl(var(--success-400) / <alpha-value>)",
				500: "hsl(var(--success-500) / <alpha-value>)",
				600: "hsl(var(--success-600) / <alpha-value>)",
				700: "hsl(var(--success-700) / <alpha-value>)",
				800: "hsl(var(--success-800) / <alpha-value>)",
				900: "hsl(var(--success-900) / <alpha-value>)",
				950: "hsl(var(--success-950) / <alpha-value>)",
				"a50": "hsl(var(--success-a50))",
				"a100": "hsl(var(--success-a100))",
				"a200": "hsl(var(--success-a200))",
				"a300": "hsl(var(--success-a300))",
				"a400": "hsl(var(--success-a400))",
			},
		},
		container: {
			center: true,
			padding: "2rem",
			screens: {
				"2xl": "1400px",
			},
		},
		extend: {
			animation: {
				"accordion-down": "accordion-down 0.2s ease-out",
				"accordion-up": "accordion-up 0.2s ease-out",
			},
			aria: {
				collapsed: 'expanded="false"',
				invalid: 'invalid="true"',
				unchecked: 'checked="false"',
			},
			backgroundColor: {
				base: "hsl(var(--bg-base))",
				card: "hsl(var(--bg-card))",
				dialog: "hsl(var(--bg-dialog))",
				form: "hsl(var(--bg-form))",
				overlay: "hsl(var(--bg-overlay))",
				popover: "hsl(var(--bg-popover))",
				tooltip: "hsl(var(--bg-tooltip))",
				"accent-active": "hsl(var(--bg-accent-active))",
				"accent-hover": "hsl(var(--bg-accent-hover))",
				"accent-muted-active": "hsl(var(--bg-accent-muted-active))",
				"accent-muted-hover": "hsl(var(--bg-accent-muted-hover))",
				"accent-muted": "hsl(var(--bg-accent-muted))",
				"base-hover": "hsl(var(--bg-base-hover))",
				"card-hover": "hsl(var(--bg-card-hover))",
				"danger-active": "hsl(var(--bg-danger-active))",
				"danger-hover": "hsl(var(--bg-danger-hover))",
				"danger-muted-active": "hsl(var(--bg-danger-muted-active))",
				"danger-muted-hover": "hsl(var(--bg-danger-muted-hover))",
				"danger-muted": "hsl(var(--bg-danger-muted))",
				"form-active": "hsl(var(--bg-form-active))",
				"form-hover": "hsl(var(--bg-form-hover))",
				"neutral-active": "hsl(var(--bg-neutral-active))",
				"neutral-hover": "hsl(var(--bg-neutral-hover))",
				"neutral-muted-active": "hsl(var(--bg-neutral-muted-active))",
				"neutral-muted-hover": "hsl(var(--bg-neutral-muted-hover))",
				"neutral-muted": "hsl(var(--bg-neutral-muted))",
				"popover-hover": "hsl(var(--bg-popover-hover))",
				"success-active": "hsl(var(--bg-success-active))",
				"success-hover": "hsl(var(--bg-success-hover))",
				"success-muted-active": "hsl(var(--bg-success-muted-active))",
				"success-muted-hover": "hsl(var(--bg-success-muted-hover))",
				"success-muted": "hsl(var(--bg-success-muted))",
				"warning-active": "hsl(var(--bg-warning-active))",
				"warning-hover": "hsl(var(--bg-warning-hover))",
				"warning-muted-active": "hsl(var(--bg-warning-muted-active))",
				"warning-muted-hover": "hsl(var(--bg-warning-muted-hover))",
				"warning-muted": "hsl(var(--bg-warning-muted))",
			},
			textColor: {
				accent: "hsl(var(--text-accent))",
				danger: "hsl(var(--text-danger))",
				default: "hsl(var(--text-default))",
				inverted: "hsl(var(--text-inverted))",
				muted: "hsl(var(--text-muted))",
				placeholder: "hsl(var(--text-placeholder))",
				strong: "hsl(var(--text-strong))",
				success: "hsl(var(--text-success))",
				warning: "hsl(var(--text-warning))",
				"accent-strong": "hsl(var(--text-accent-strong))",
				"danger-strong": "hsl(var(--text-danger-strong))",
				"neutral-strong": "hsl(var(--text-neutral-strong))",
				"success-strong": "hsl(var(--text-success-strong))",
				tooltip: "hsl(var(--text-tooltip))",
				"warning-strong": "hsl(var(--text-warning-strong))",
			},
			borderColor: {
				accent: "hsl(var(--border-accent))",
				base: "hsl(var(--border-base))",
				card: "hsl(var(--border-card))",
				danger: "hsl(var(--border-danger))",
				dialog: "hsl(var(--border-dialog))",
				form: "hsl(var(--border-form))",
				neutral: "hsl(var(--border-neutral))",
				popover: "hsl(var(--border-popover))",
				success: "hsl(var(--border-success))",
				warning: "hsl(var(--border-warning))",
				"accent-muted": "hsl(var(--border-accent-muted))",
				"base-muted": "hsl(var(--border-base-muted))",
				"card-muted": "hsl(var(--border-card-muted))",
				"danger-muted": "hsl(var(--border-danger-muted))",
				"dialog-muted": "hsl(var(--border-dialog-muted))",
				"neutral-muted": "hsl(var(--border-neutral-muted))",
				"popover-muted": "hsl(var(--border-popover-muted))",
				"success-muted": "hsl(var(--border-success-muted))",
				"warning-muted": "hsl(var(--border-warning-muted))",
			},
			ringColor: {
				accent: "hsl(var(--ring-accent))",
				danger: "hsl(var(--ring-danger))",
				neutral: "hsl(var(--ring-neutral))",
				success: "hsl(var(--ring-success))",
				warning: "hsl(var(--ring-warning))",
			},
			cursor: {
				inherit: "inherit",
				initial: "initial",
			},
			data: {
				"active-item": "active-item",
				"orientation-horizontal": 'orientation="horizontal"',
				"orientation-vertical": 'orientation="vertical"',
				"side-bottom": 'side="bottom"',
				"side-left": 'side="left"',
				"side-right": 'side="right"',
				"side-top": 'side="top"',
				"state-checked": 'state~="checked"',
				"state-closed": 'state~="closed"',
				"state-indeterminate": 'state~="indeterminate"',
				"state-open": 'state~="open"',
				"state-selected": 'state~="selected"',
				"state-unchecked": 'state~="unchecked"',
				disabled: "disabled",
				highlighted: "highlighted",
			},
			fontFamily: {
				sans: ["EuclidSquare", ...defaultTheme.fontFamily.sans],
				mono: ["IBMPlexMono", ...defaultTheme.fontFamily.mono],
			},
			fontSize: {
				"size-inherit": "inherit",
			},
			fontWeight: {
				initial: "initial",
			},
			keyframes: {
				"accordion-down": {
					from: { height: "0" },
					to: { height: "var(--radix-accordion-content-height)" },
				},
				"accordion-up": {
					from: { height: "var(--radix-accordion-content-height)" },
					to: { height: "0" },
				},
			},
			lineHeight: {
				0: "0",
				initial: "initial",
			},
			screens: {
				xs: "480px",
			},
			spacing: {
				"1.25": "0.3125rem",
			},
			transitionProperty: {
				"max-height": "max-height",
			},
			zIndex: {
				1: "1",
				max: "2147483647",
			},
		},
	},
	plugins: [
		tailwindCssAnimatePlugin,
		firefoxVariantPlugin,
		plugin(function ({ addVariant }) {
			addVariant("dark-high-contrast", [":is(.dark-high-contrast &)"]);
			addVariant("high-contrast", [":is(.light-high-contrast &)"]);
		}),
	],
} satisfies Config;

export type MantlePreset = typeof mantlePreset;

export { mantlePreset };
