import { createContext, type ComponentProps } from "react";
import { parseValidation, type ValidationState } from "./validation.js";

/**
 * ARIA and identity props that `Field.Control` applies to the field's
 * focusable control. `id` and `name` come from the surrounding `Field.Item`
 * so a caller only needs to declare `name` once.
 */
type FieldControlAriaProps = {
	/**
	 * IDREFs for helper or error text that describe the focusable control.
	 */
	"aria-describedby"?: string;
	/**
	 * IDREFs for error text that represent the control's current error state.
	 */
	"aria-errormessage"?: string;
	/**
	 * The resolved ARIA invalid state for the focusable control.
	 */
	"aria-invalid"?: ComponentProps<"input">["aria-invalid"];
	/**
	 * Stable DOM id for the focusable control, generated by `Field.Item` and
	 * also used as `Field.Label`'s default `htmlFor`.
	 */
	id?: string;
	/**
	 * Form value identity from `Field.Item`'s required `name` prop.
	 */
	name?: string;
};

/**
 * Context value owned by `Field.Item` and consumed by message/control parts.
 *
 * `Field.Item` owns the two stable slot IDs (one for the description, one for
 * the error list) so consumers don't manage ARIA wiring themselves. The IDs
 * are emitted unconditionally; ARIA treats unresolved IDREFs as no-ops, so
 * dangling IDs (when no description or error list is rendered) are harmless.
 */
type FieldItemContextValue = {
	/**
	 * Stable DOM id applied to the `Field.Control` child and consumed by
	 * `Field.Label` as the default `htmlFor` target.
	 */
	controlId: string;
	/**
	 * Stable ID for the rendered `Field.Description` slot, generated once per
	 * `Field.Item`.
	 */
	descriptionId: string;
	/**
	 * Stable ID for the rendered `Field.Errors` / `Field.ErrorList` slot,
	 * generated once per `Field.Item`.
	 */
	errorId: string;
	/**
	 * Form-value name for the field, supplied by the required `name` prop on
	 * `Field.Item` and splatted onto the `Field.Control` child.
	 */
	name: string;
	/**
	 * `true` while a non-empty `Field.Errors` / `Field.ErrorList` is mounted
	 * under this `Field.Item`. Used by `Field.Item` to infer an `"error"`
	 * validation state when no explicit `validation` prop is supplied.
	 */
	hasErrors: boolean;
	/**
	 * Marks a non-empty `Field.Errors` / `Field.ErrorList` as mounted. Returns
	 * its cleanup callback.
	 */
	registerError: () => () => void;
	/**
	 * Validation state inferred or supplied by the surrounding `Field.Item`.
	 */
	validation?: ValidationState;
};

/**
 * Options for resolving the ARIA props that `Field.Control` applies.
 */
type ResolveFieldControlAriaPropsOptions = {
	/**
	 * The nearest `Field.Item` context, when the control is rendered inside one.
	 */
	context: FieldItemContextValue | null;
};

/**
 * Context shared by the parts of a single `Field.Item`.
 */
const FieldItemContext = createContext<FieldItemContextValue | null>(null);

/**
 * Context published by `Field.Control` carrying the resolved ARIA / identity
 * props that should land on the focusable control. Mantle compound triggers
 * (`Select.Trigger`, `MultiSelect.Trigger`, …) consume this so wrapping a
 * compound widget in `Field.Control` works — `cloneElement` only reaches the
 * direct child, which for a compound widget is a context provider that does
 * not forward ARIA props to its inner trigger.
 *
 * `null` when no `Field.Control` is in the tree.
 */
const FieldControlContext = createContext<FieldControlAriaProps | null>(null);

/**
 * Resolves the ARIA, identity, and validation props that `Field.Control`
 * applies to its focusable child. `Field.Item` is the single source of truth
 * for `id`, `name`, `aria-*`, and `validation` — the resolver reads only the
 * surrounding `Field.Item` context and ignores anything supplied on the child
 * element. To override these values, set them on `Field.Item` itself.
 */
const resolveFieldControlAriaProps = ({ context }: ResolveFieldControlAriaPropsOptions) => {
	if (!context) {
		return {
			ariaProps: {} as const satisfies FieldControlAriaProps,
			validation: undefined,
		};
	}

	const parsedValidation = parseValidation({
		defaultAriaInvalid: false,
		validation: context.validation,
	});
	// Always emit both slot IDs in aria-describedby when inside a Field.Item.
	// Per WAI-ARIA, unresolved IDREFs are ignored by assistive tech, so the
	// dangling ID is harmless when the corresponding slot isn't rendered and
	// lets us skip mount-time bookkeeping. aria-errormessage is additionally
	// spec-gated on aria-invalid="true", so it stays inert until the field is
	// actually invalid.
	const ariaDescribedBy = `${context.descriptionId} ${context.errorId}`;
	const ariaErrorMessage = parsedValidation.isInvalid ? context.errorId : undefined;

	return {
		ariaProps: {
			"aria-describedby": ariaDescribedBy,
			"aria-errormessage": ariaErrorMessage,
			"aria-invalid": parsedValidation.ariaInvalid,
			id: context.controlId,
			name: context.name,
		} satisfies FieldControlAriaProps,
		validation: parsedValidation.validation,
	};
};

export {
	//,
	FieldControlContext,
	FieldItemContext,
	resolveFieldControlAriaProps,
};
export type {
	//,
	FieldControlAriaProps,
	FieldItemContextValue,
};
