name: Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  release:
    types: [published]
  workflow_dispatch: # Can be manually run as well

jobs:
  prod-deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        # use version from package.json#packageManager field

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest turbo@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
