name: highlight-server

on:
  push:
    branches:
      - main
    paths:
      - "apps/highlight-server/**"
      - "packages/mantle/src/components/code-block/**"
      - "packages/mantle-server-syntax-highlighter/**"
      - ".github/workflows/publish-highlight-server.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ngrok-oss/mantle/highlight-server

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'ngrok-oss/mantle'
    steps:
      - uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/highlight-server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
