name: Vercel

permissions:
  contents: read
  pull-requests: write

env:
  DO_NOT_TRACK: 1
  TURBO_TELEMETRY_DISABLED: 1
  VERCEL_TELEMETRY_DISABLED: 1
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

on:
  release:
    types: [published]
  workflow_dispatch: # Can be manually run as well

jobs:
  prod-deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        # use version from package.json#packageManager field
        with:
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Dependencies 📥
        run: |
          pnpm install

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest turbo@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
