name: test-slack-comment
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        # use version from package.json#packageManager field

      - run: pnpm install

      - name: Grab the version and store it in an env variable
        run: |
          VERSION=$(jq -r '.version' ./packages/mantle/package.json)
          echo "MANTLE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Post to slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PUBLISH_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"`@ngrok/mantle@${{ env.MANTLE_VERSION }}` published to npm!\n[Release Notes](https://github.com/ngrok-oss/mantle/releases/tag/v${{ env.MANTLE_VERSION }})"}' $SLACK_WEBHOOK_URL
